Repository openshift/k8s-prometheus-adapter, pull requests merged in 2023-11, with the labels that each got.

#88 OCPBUGS-21621: Add a toggle to disable HTTP/2 on the server to mitigate CVE-2023-44487
  cmd/adapter/adapter.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#89 OCPBUGS-21473: Add a toggle to disable HTTP/2 on the server to mitigate CVE-2023-44487
  cmd/adapter/adapter.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#87 [release-4.11] OCPBUGS-21652: limit number of simultaneous client requests
  pkg/client/api.go
  pkg/client/limiter.go
  pkg/client/limiter_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#94 MON-3489: Bump openshift/k8s-prometheus-adapter to v0.11.2
  Makefile
  VERSION
  deploy/manifests/api-service.yaml
  deploy/manifests/cluster-role-aggregated-metrics-reader.yaml
  deploy/manifests/cluster-role-binding-delegator.yaml
  deploy/manifests/cluster-role-binding.yaml
  deploy/manifests/cluster-role-metrics-server-resources.yaml
  deploy/manifests/cluster-role.yaml
  deploy/manifests/config-map.yaml
  deploy/manifests/deployment.yaml
  deploy/manifests/network-policy.yaml
  deploy/manifests/pod-disruption-budget.yaml
  deploy/manifests/role-binding-auth-reader.yaml
  deploy/manifests/service-account.yaml
  deploy/manifests/service.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only
